### PR TITLE
More updates for building Pytorch extensions in Transformer Engine

### PR DESCRIPTION
**Pull request by wenchenvincent**

### CODE REVIEW

**Comment by pruthvistony** [comment]
> @jithunnair-amd @pruthvistony I saw that Pytorch repo has a hard copy of hipify_torch. How often do we update the hard copy of hipify_torch in python? We will need the updates here to be in pytorch for Transformer Engine.

@wenchenvincent ,
pyTorch repo is having a separate copy of hipify and we have plans to migrate it to hipify_torch. Till this is done, if you need changes in pyTorch code you will need to push change into pytorch repo hipify code and also to hipify_torch repo (if this is used in other repos like transformers,etc...).

**Review by pruthvistony — APPROVED** [review]

**Comment by wenchenvincent** [comment]
> > @jithunnair-amd @pruthvistony I saw that Pytorch repo has a hard copy of hipify_torch. How often do we update the hard copy of hipify_torch in python? We will need the updates here to be in pytorch for Transformer Engine.
> 
> @wenchenvincent , pyTorch repo is having a separate copy of hipify and we have plans to migrate it to hipify_torch. Till this is done, if you need changes in pyTorch code you will need to push change into pytorch repo hipify code and also to hipify_torch repo (if this is used in other repos like transformers,etc...).

By "migrating it to hipify_torch", do you mean making hipify_torch a submodule of pytorch? So for now, every time we need to update hipify_torch, we would send PRs to both hipify_torch and pytorch, right?

**Comment by pruthvistony** [comment]
Yes, hipify_torch will be added a submodule to pytorch. 
But till it is done, if we have a change to hipify we will need separate PRs, one for pytorch repo and another into hipify_torch repo.

**Comment by wenchenvincent** [comment]
> Yes, hipify_torch will be added a submodule to pytorch, this is the plan :). But till it is done, if we have a change to hipify we will need separate PRs, one for pytorch repo and another into hipify_torch repo.

BTW, I am not familiar with filing PRs for Pytorch. Do we just put a PR against ROCmSoftwarePlatform/pytorch:master? How do we upstream the changes?

**Comment by jithunnair-amd** [comment]
> BTW, I am not familiar with filing PRs for Pytorch. Do we just put a PR against ROCmSoftwarePlatform/pytorch:master? How do we upstream the changes?

@wenchenvincent You'd file a PR on pytorch/pytorch:master.

**Pull request merged**
