### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bmedishe**
Test jenkins hipify_torch ci

### CODE REVIEW

**Comment by bmedishe** [comment]
test pytorch please

**Comment by okakarpa** [comment]
retest this please

**Comment by bmedishe** [comment]
test pytorch please

**Comment by bmedishe** [comment]
retest this please

**Comment by bmedishe** [comment]
retest this please

**Comment by okakarpa** [comment]
retest this please

**Comment by bmedishe** [comment]
retest this please

**Comment by bmedishe** [comment]
retest this please

**Comment by bmedishe** [comment]
retest this please

**Comment by bmedishe** [comment]
retest this please

**Comment by bmedishe** [comment]
retest this please

**Pull request closed without merging**
