### PR TITLE
Use absolute paths for all file names to hipify.

### PR DESCRIPTION
**Pull request by wenchenvincent**
This fixes issues where some files with names in relative paths were not handled correctly.

### CODE REVIEW

**Review by pruthvistony — APPROVED** [review]

**Comment by pruthvistony** [comment]
@wenchenvincent ,
The changes looks fine. But I havent come across this error. Can you please explain what was the issue happening due to relative paths for my understanding. Also I am not if any side effects of this change.

**Comment by wenchenvincent** [comment]
I had two issues, which were addressed by the two additions in the PR:

I had some relative paths in the header_include_dirs. So the all_files list would include the relative paths of these header files. But when hipify_torch was processing the include lines in a file, it would look up using the absolute file path. So those include will not be replaced with their hipified header files. I had to use the absolute path to work around this, but I felt it would be more robust to have hipify_torch do it.

I had some relative paths in the cuda_source_list. When [replace_cuda_with_hip_files.py](https://github.com/ROCmSoftwarePlatform/hipify_torch/pull/44/files#diff-10aa4caab6971464aa7ac503528e8f748e8c796c48bfe8253b5a8b1140725cea) looks for the hipified list, hipified_result dict uses absolute paths as keys. So we would also need to supply the cuda_source_list with absolute paths.

**Comment by jithunnair-amd** [comment]
Requested @wenchenvincent to provide reproductions details offline for further debug. At first glance, it seems that the change in  `hipify_python.py` should not be required, but the change in `replace_cuda_with_hip_files.py` looks correct.

**Review by jithunnair-amd — APPROVED** [review]
LGTM

**Pull request merged**
