### PR TITLE
Sync the updates from upstream PyTorch changes 

### PR DESCRIPTION
**Pull request by lcskrishna**
Syncing the changes from upstream PyTorch into this repo. 

This PR is required to enable https://github.com/pytorch/pytorch/pull/101391

### CODE REVIEW

**Review by pruthvistony — CHANGES_REQUESTED** [review]
ROCmSoftwarePlatform/master is not more being used.

ROCmSoftwarePlatform/main is default branch, which is essential a copy of upstream main branch. 

I believe ROCmSoftwarePlatform/rocm5.7_internal_testing should be updated if any changes requried.
And regarding upstream changes ROCmSoftwarePlatform/main is almost in sync may be missing few commits, which will be pulled in after next IFU.

**Comment by pruthvistony** [comment]
ROCmSoftwarePlatform/main should be updated only by the IFU process and then merge the commits to internal_testing branch.

**Review by pruthvistony — APPROVED** [review]
Was thinking of rocm_version default set to 5.0, since rocm_version.h file could be missing in older version, but setting to 0.0 should be fine IHOP.

**Review by alugorey — APPROVED** [review]
lgtm

**Review by jithunnair-amd — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@lcskrishna I'll go ahead and merge this PR since the CI needs work to test hipify_torch properly. But it's probably most productive to work on that after we get our upstream PR to integrate hipify_torch resolved.

**Comment by jithunnair-amd** [comment]
@lcskrishna Isn't this dead code now? https://github.com/ROCmSoftwarePlatform/hipify_torch/blob/5a31d54d3fce6ffa48031142d1d2b6032424dacb/hipify_torch/hipify_python.py#L499

**Comment by lcskrishna** [comment]
> @lcskrishna Isn't this dead code now?
> 
> https://github.com/ROCmSoftwarePlatform/hipify_torch/blob/5a31d54d3fce6ffa48031142d1d2b6032424dacb/hipify_torch/hipify_python.py#L499

Yes, it is dead now. Let me remove this dead code.

**Pull request merged**
